### ISSUE TITLE
BAT91 not working

### ISSUE THREAD

**Issue by Dunkelicht** [AveYo/res2batch#7]
for a large file more than 3mb, it said:

![2021-11-04_01-27-43](https://user-images.githubusercontent.com/22488565/140156359-ede5be7c-5e1a-4ab0-a87f-b1f6542fb732.png)

Neither works for win7 or win10.

but for BAT85, it works.

I need to paste to somewhere do not accept %*, so how do I fix it? 

Thank you all! 

`Unable to find type [BAT91]: make sure that the assembly containing this type is loaded.
At line:8 char:56
+ '@; cd -Lit($env:__CD__); function X([int]$x=1){[BAT91] <<<< ::Dec([ref]$f,$x+1,$x,$k); expand -R $x -F:* .; del $x -
force}
    + CategoryInfo          : InvalidOperation: (BAT91:String) [], RuntimeException
    + FullyQualifiedErrorId : TypeNotFound

Microsoft (R) File Expansion Utility  Version 6.1.7600.16385
Copyright (c) Microsoft Corporation. All rights reserved.

Can't open input file: 1.

Remove-Item : Cannot find path 'C:\_\7z\1' because it does not exist.
At line:8 char:107
+ '@; cd -Lit($env:__CD__); function X([int]$x=1){[BAT91]::Dec([ref]$f,$x+1,$x,$k); expand -R $x -F:* .; del <<<<  $x -
force}
    + CategoryInfo          : ObjectNotFound: (C:\_\7z\1:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
`

**Comment by Dunkelicht** [comment]
update: 6.1 works fine for file size 320k, while 6.3 does not, I did not know why and how to debug it....

500kb for 6.1 shows:
![6 1notworking](https://user-images.githubusercontent.com/22488565/140560981-489c5808-1d9e-4d16-b766-cb974fe0cfe1.png)

**Comment by Dunkelicht** [comment]
Another bug, if compressed target does not exit, this script may dell this user all files listed in C:\users , it exits in 6.1. 
I did not test for 6.3. Be cautions.

**Comment by Dunkelicht** [comment]
some files could be txted, some not...

**Comment by AveYo** [comment]
There must be something wrong with the configuration you're using, 
because none of the issues you've mentioned have ever been reported,
and the script has been working for huge files just fine.
Maybe it's a copy-paste error? did you use `Code` - `Download ZIP` button in github?

In any case, in v6.4 I've changed a few things to hopefully prevent your issues

**Comment by Dunkelicht** [comment]
Thanks a lot for replying and updating!

As it crashes randomly, I think it is the encode reason. I all use BAT85 to prevent char like (*%.

What I try to encode file is a PDF: 
https://support.industry.siemens.com/cs/attachments/109479728/109479728_LGF_TIAV16_DOC_V5_0_0_en.pdf 
refer to : https://support.industry.siemens.com/cs/ww/en/view/109479728

I tried when region and language setting to Non-English like below and it still crashes... 

![2021-11-08_09-22-37](https://user-images.githubusercontent.com/22488565/140670701-1d7792de-6fbb-4e06-8a52-c8cd8e6a941a.png)

![2021-11-08_09-22-06](https://user-images.githubusercontent.com/22488565/140670708-3889cb06-68d6-4189-b429-d7803853762d.png)

![2021-11-08_09-09-54](https://user-images.githubusercontent.com/22488565/140670177-1364a746-e866-4f97-b7de-7f4d33ef61f7.png)

In 6.4 the problem exists... 

![2021-11-08_09-11-56](https://user-images.githubusercontent.com/22488565/140669913-875bfa97-14c9-479b-890d-3fae361dcb72.png)

Thanks a lot for updating!

**Comment by AveYo** [comment]
v6.5 at least fixed the issue with BAT85 (because BAT91 worked fine, that's what I personally use a lot)

**Comment by Dunkelicht** [comment]
> 
> 
> v6.5 at least fixed the issue with BAT85 (because BAT91 worked fine, that's what I personally use a lot)

Thanks again for updating! 

In windows 7 there is a also warning, but the BAT85 is working now.

I will test some other file as far as I could.


![v6 5 some warinning ](https://user-images.githubusercontent.com/22488565/141689874-6bc6a4a8-5590-4fb7-b498-774139b6220f.png)

**Comment by AveYo** [comment]
Yeah, no idea why that warning, I can't replicate it in my windows 7 vm  
It's related to the cleanup part, so not critical _(if you get leftover random-named folders you can clean them up manually)_

**Comment by Dunkelicht** [comment]
> 
> 
> Yeah, no idea why that warning, I can't replicate it in my windows 7 vm It's related to the cleanup part, so not critical _(if you get leftover random-named folders you can clean them up manually)_

Thanks for everything, please consider some protection for NULL input, it was dangerous, delete all C:\Users\[UserName].

This issue could be closed by now.

**Comment by AveYo** [comment]
the way SendTo works the input can't be null, isn't it?  
but I do test anyway:  
`if (!(test-path -lit $($arg[0].Value.Trim('"')))) {write-host "ERROR! path not found" -fore Yellow; timeout -1; return}`
