### ISSUE TITLE
The folder is empty after decompression

### ISSUE THREAD

**Issue by Davider-code** [AveYo/res2batch#9]
see gif pic

![abc](https://user-images.githubusercontent.com/6350504/141665393-5f3bb947-8dd4-4601-8544-39a40495795d.gif)

test files:
[test.zip](https://github.com/AveYo/Compressed2TXT/files/7533091/test.zip)

**Comment by AveYo** [comment]
you were using v6.1 not the latest
tho even v6.4 had a bug with BAT85
fixed in v6.5

thanks for your detailed report!

**Comment by Davider-code** [comment]
> you were using v6.1 not the latest tho even v6.4 had a bug with BAT85 fixed in v6.5
> 
> thanks for your detailed report!

Thank you very much for your reply
